- src/components/popover/popover.scss
- src/components/popover/popover.spec.ts
- src/components/popover/popover.ts
- src/components/select/README.md
- src/components/select/index.ts
- src/components/select/option.html
- src/components/select/option.ts
- src/components/select/package.json
- src/components/select/select.html
- src/components/select/select.scss
- src/components/select/select.spec.ts
- src/components/select/select.ts
- src/components/system-config-spec.ts
- src/e2e-app/app/app.component.html
- src/e2e-app/app/app.component.ts
- src/e2e-app/app/app.module.ts
- src/e2e-app/app/popover/popover.component.html
- src/e2e-app/app/select/select.component.html
- src/e2e-app/app/select/select.component.ts
I have made initial version of select. I tried to make it similar to https://material.angularjs.org/latest/demo/select
Testing it browser it worked fine, but have problem with change detection in tests.
> Add select

- src/components/popover/popover.scss
- src/components/popover/popover.ts
- src/components/select/select.html
- src/components/select/select.scss
- src/components/select/select.ts
- src/e2e-app/app/select/select.component.html
- fix close select on clicking other select
- add disabled state
> Select visual improvements

- src/components/select/README.md
- src/components/select/package.json
> Add peer dependency @angular2-mdl-ext/popover

- src/components/popover/package.json
- src/components/popover/popover.spec.ts
- src/components/popover/popover.ts
* Add test for hide popover on click outside of popover
* Remove window click / touchstart events listeners on component destroy
> Popover hide

- src/components/select/select.spec.ts
- src/components/select/select.ts
- src/e2e-app/app/popover/popover.component.html
- src/e2e-app/app/select/select.component.html
- src/e2e-app/app/select/select.component.ts
- src/e2e-app/css/style.scss
- Add dynamic multiselect
- changes examples for Select
> Add dynamic multiselect

- README.md
- src/components/popover/package.json
- src/components/popover/popover.ts
- src/components/select/package.json
- src/components/select/select.ts
- src/e2e-app/css/style.scss
> component styling

- src/components/select/package.json
- src/components/select/select.spec.ts
- src/components/select/select.ts
* Bump select version
* Fixes #41 Unable to select on options change - Trigger bindOptions() when options change
* Fix #38 BrowserModule is imported into Select Component - CommonModule should be imported instead as described on https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-browser-vs-common-module
> Select fixes

- src/components/popover/package.json
@mseemann I have bumped wrong package version in previous PR
> Bump popover version after refactor event listening on document

- src/components/select/select.html
- src/components/select/select.scss
- src/components/select/select.ts
- src/e2e-app/app/select/select.component.html
- src/e2e-app/app/select/select.component.ts
Added grey placeholder text and added the float label option to mdl-select.
> Fix for #116 with float label support

- src/components/select/select.ts
- src/e2e-app/app/select/select.component.html
https://github.com/mseemann/angular2-mdl-ext/issues/143
> onArrowDown method fixed, for non-default option case

- src/components/select/select.spec.ts
- src/components/select/select.ts
I've added some basic concept for search at select component. Hope to see some fedback.
> keyboard search mechanism for select component added

- README.md
I think you lack demo page navigation for both select/popover components.
> navigation to demo page added to README.md

- src/components/select/select.ts
- src/e2e-app/app/select/select.component.ts
After merging "keyboard search mechanism" (https://github.com/mseemann/angular2-mdl-ext/commit/36421562604a37e0d975c1029c8915a0684ee531) I encountered issue with scrolling options list for greater options count. The current implementation does not cover the new feature, so I added some improvement:
- already selected option is vertically centered over the list (where possible),
- more options to e2e app has been added (to see how it behaves).
What you think?
> select component - scrolling list behavior improved

- src/components/expansion-panel/README.md
- src/components/expansion-panel/expansion-panel.component.ts
- src/components/expansion-panel/expansion-panel.scss
- src/components/expansion-panel/expansion-panel.spec.ts
- src/components/expansion-panel/index.ts
- src/components/expansion-panel/package.json
- src/components/system-config-spec.ts
- src/e2e-app/app/app.component.html
- src/e2e-app/app/app.component.scss
- src/e2e-app/app/app.component.ts
- src/e2e-app/app/app.module.ts
- src/e2e-app/app/expansion-panel/expansion-panel.component.html
- src/e2e-app/app/expansion-panel/expansion-panel.component.ts
- src/e2e-app/css/style.scss
- tools/gulp/tasks/build.ts
- tools/gulp/tasks/test.ts
Initial implementation for issue #35
> expansion panel

- src/components/select/select.ts
> Render value after options change

- src/components/select/package.json
- src/components/select/select.ts
@mseemann This PR is for fixing the aot issues in angular2 branch. It has the changes from the commit d80e35cd076653463293ffca6560f517061c4548 on master
Thanks,
racerhere
> fix aot issue; bump patch version

- src/components/select/package.json
- src/components/select/select.ts
@mseemann , AOT does not like the `@Output()` parameters  to be private. Please let me know if these changes can be merged. Thank you!
> fix more aot problems; bump patch version

- src/components/select/package.json
- src/components/select/select.html
Dont render select options when they are not visible to speed up select rendering
> Dont render select options when they are not visible

- src/components/popover/package.json
- src/components/popover/popover.ts
> Single document click listener for all popovers via registry, fixes #978

- src/components/select/select.ts
> fix(mdl-select): make onFocus and onInputFocus public

- src/components/select/README.md
- src/components/select/option.html
- src/components/select/option.ts
- src/components/select/select.scss
- src/e2e-app/app/select/select.component.html
- src/e2e-app/app/select/select.component.ts
#657 [Feature request] Add disabled option for mdl-option
> Add disabled to mdl-select option

- src/components/select/select.ts
the build was failing while this was private
> needed to change var to public so that building with --prod would work
